name: cs Update Checker

env:
  REPO_URL: https://github.com/sfwtw/Actions-LEDE-Fine3399
  REPO_BRANCH: main
  TZ: Asia/Shanghai  # 设置时区为中国时间

on:
  workflow_dispatch:  # 支持手动触发
  # schedule:
    # - cron: '0 */12 * * *'  # 每12小时运行一次

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      actions: write      # 工作流权限
      contents: read      # 仓库读取权限
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 获取上次提交记录
        id: getLastHash
        run: |
          if [ -f .commitHash ]; then
            echo "lastHash=$(cat .commitHash)" >> $GITHUB_OUTPUT
          else
            echo "lastHash=" >> $GITHUB_OUTPUT
          fi
        
      - name: 获取最新提交信息
        id: getHash
        run: |
          mkdir -p workspace
          cd workspace
          git clone --depth 100 $REPO_URL -b $REPO_BRANCH . || exit 1
          if [ -f ../.commitHash ]; then
            current_hash=$(cat ../.commitHash)
          else
            current_hash=$(git rev-parse HEAD)
          fi
          echo "commitHash=$current_hash" >> $GITHUB_OUTPUT
                    
          if [ ! -z "${{ steps.getLastHash.outputs.lastHash }}" ]; then
            echo "最新提交变更:" > ../commit_msg.txt
            echo "-------------------" >> ../commit_msg.txt
            git log --pretty=format:'%h - %s' ${{ steps.getLastHash.outputs.lastHash }}..$current_hash | 
            awk '{print "["NR"] "$0"\n"}' >> ../commit_msg.txt
            echo "-------------------" >> ../commit_msg.txt
            echo "commitTitle=$(cat ../commit_msg.txt)" >> $GITHUB_OUTPUT
          fi

      - name: 比对提交哈希值
        id: cacheHash
        uses: actions/cache@v3
        with:
          path: .commitHash
          key: commitHash_${{ steps.getHash.outputs.commitHash }}
          restore-keys: |
            commitHash_

      - name: 保存新的提交哈希值
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

      - name: 触发编译
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ github.repository }}
          event-type: test
          client-payload: |
            {
              "ref": "${{ github.ref }}",
              "sha": "${{ steps.getHash.outputs.commitHash }}",
              "commit_msg": "${{ steps.getHash.outputs.commitTitle }}"
            }

      - name: 清理旧的工作流记录
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 0
          keep_minimum_runs: 2
          # delete_workflow_pattern: update-checker.yml  # 只清理当前工作流
