name: cs Update Checker

env:
  REPO_URL: https://github.com/sfwtw/Actions-LEDE-Fine3399
  REPO_BRANCH: main
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      has_updates: ${{ steps.check_updates.outputs.has_updates }}
    
    steps:
      - name: 检查更新
        id: check_updates
        run: |
          set -e
          echo "::group::克隆仓库"
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH temp
          cd temp
          
          # 获取最新提交信息
          LATEST_COMMIT=$(git rev-parse HEAD)
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")
          
          echo "最新提交: ${LATEST_COMMIT}"
          echo "提交信息: ${COMMIT_MSG}"
          echo "::endgroup::"
          
          if [ -n "$(git log -1)" ]; then
            echo "检测到更新，触发编译..."
            echo "has_updates=true" >> $GITHUB_OUTPUT
            
            # 触发编译工作流
            curl -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token ${{ secrets.TOKEN }}" \
              -d "{\"event_type\":\"test\"}" \
              || echo "触发编译失败，请检查 TOKEN 权限"
          else
            echo "没有检测到更新"
            echo "has_updates=false" >> $GITHUB_OUTPUT
          fi

      - name: 清理工作流记录
        if: always()
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
